/**
 * Prisma client singleton.
 *
 * Generated by `pnpm db:generate`. The generated client lives under
 * node_modules/.pnpm/.../@prisma/client and is resolved via the import below.
 */
import { PrismaClient } from "@prisma/client";

declare global {
  // eslint-disable-next-line no-var
  var __prisma: PrismaClient | undefined;
}

export const prisma: PrismaClient =
  globalThis.__prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === "production" ? ["error", "warn"] : ["error", "warn", "query"],
  });

if (process.env.NODE_ENV !== "production") {
  globalThis.__prisma = prisma;
}
